### PR TITLE
deprecated bases in kustomization files

### PR DESCRIPTION
**Pull request by jnunyez**
manifest validation depends on [8](https://github.com/redhat-partner-solutions/vse-carslab-hub/pull/8)

### CODE REVIEW

**Comment by natifridman** [comment]
Need to resolve conflicts

**Comment by jnunyez** [comment]
> Need to resolve conflicts

sorry, not folowing. Conflicts with?

**Comment by natifridman** [comment]
```
Conflicting files
core/openshift-pipelines/kustomization.yaml
```

**Comment by jnunyez** [comment]
> ```
> Conflicting files
> core/openshift-pipelines/kustomization.yaml
> ```

I just understood what you meant yesterday. Thks!

**Review by natifridman — APPROVED** [review]
LGTM

**Pull request merged**
