### PR TITLE
demo1 build image and run sriov test suites

### PR DESCRIPTION
**Pull request by jnunyez**
- Includes PipelineRuns to build cnf-gotests image and run sriov tests with cnf-gotests
- Depends on updated vse-catalog
- **TODO**: Add ApplicationSet to trigger demo
- **Instructions** to add run sriov tests to be polished in doc
- **Discuss** commit 4c8bbe3d696927238fce873898021c3e58b372fa in the PR

### CODE REVIEW

**Review by natifridman — COMMENTED** [review]
I'm not sure if pipeline runs should be part of this repo...

**Comment by jnunyez** [comment]
> I'm not sure if pipeline runs should be part of this repo...

After the last changes I tend to think PipelineRuns could live in vse-catalog. What do you think?

**Comment by natifridman** [comment]
> After the last changes I tend to think PipelineRuns could live in vse-catalog. What do you think?

I tend to agree

**Comment by jnunyez** [comment]
> > After the last changes I tend to think PipelineRuns could live in vse-catalog. What do you think?
> 
> I tend to agree



> > After the last changes I tend to think PipelineRuns could live in vse-catalog. What do you think?
> 
> I tend to agree

Done. Requires [vse-catalog-PR16](https://github.com/redhat-partner-solutions/vse-catalog/pull/16) to before merge

**Review by natifridman — COMMENTED** [review]
`clusters` folder should contain only the cluster deployment config.
I think this should go to a new `tekton` folder under `components` 

So the structure should be
```
├components
├──tekton
├────pipelines
├────pipelineruns
├────tasks
```
Agree on the fact that clusters should contain only cluster deployment information. Bear in mind however that when run pipeline there is specific parameters related to the cluster. Something like this:

```
tekton
    └── pipelineruns
        └── volante (here goes the kustomization file triggering pipelineRun)
```

**Comment by natifridman** [comment]
> Agree on the fact that clusters should contain only cluster deployment information not the files triggering the execution of a pipelne. Bear in mind however that when run pipeline there is specific parameters related to the cluster. We should add the cluster name maybe inside as subfolder. Something like this inside `components` folder:
> 
> ```
> tekton
>        └── pipelineruns
>                   └── volante
>                              ├── build-sriov ((here goes the kustomization file triggering pipelineRun))
>                              └── run-sriov (here goes the kustomization file triggering pipelineRun)
> ```

Sounds good, so the app/appset can check the cluster folder

**Comment by jnunyez** [comment]
Needs to squash commits before merge.

**Review by natifridman — APPROVED** [review]

**Pull request merged**
