### PR TITLE
Fix du3 du4 nmstate naming

### PR DESCRIPTION
**Pull request by jnunyez**

### CODE REVIEW

**Comment by jnunyez** [comment]
Requires rebase with main.

**Review by novacain1 — CHANGES_REQUESTED** [review]
Looks good and I see your changes align to making sure the InfraEnv CR, although can you squash commits here?

**Comment by jnunyez** [comment]
> Looks good and I see your changes align to making sure the InfraEnv CR, although can you squash commits here?

Done. Ready for merge.

**Review by novacain1 — APPROVED** [review]
looks good

**Pull request merged**
